[/]
color-shading-type='solid'
picture-options='zoom'
picture-uri='file:///home/tomc/.local/share/backgrounds/2025-04-18-02-57-16-13966922-fda2-42af-bab7-5c7d96bbfa28.jpg'
picture-uri-dark='file:///home/tomc/.local/share/backgrounds/2025-04-18-02-57-16-13966922-fda2-42af-bab7-5c7d96bbfa28.jpg'
primary-color='#000000000000'
secondary-color='#000000000000'
show-desktop-icons=true
