[legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
audible-bell=false
background-color='rgb(31,33,34)'
bold-color='rgb(255,255,255)'
bold-color-same-as-fg=false
bold-is-bright=false
cursor-background-color='rgb(18,193,0)'
cursor-blink-mode='on'
cursor-colors-set=true
cursor-shape='block'
custom-command='/bin/fish'
default-size-columns=110
default-size-rows=30
font='Lilex Nerd Font Mono 11'
foreground-color='rgb(217,228,226)'
highlight-background-color='rgb(234,221,221)'
highlight-colors-set=true
highlight-foreground-color='rgb(35,31,31)'
palette=['rgb(46,52,54)', 'rgb(204,0,0)', 'rgb(101,198,9)', 'rgb(242,198,0)', 'rgb(66,129,210)', 'rgb(158,108,167)', 'rgb(6,152,154)', 'rgb(211,215,207)', 'rgb(135,139,132)', 'rgb(239,41,41)', 'rgb(138,226,52)', 'rgb(252,233,79)', 'rgb(114,159,207)', 'rgb(173,127,168)', 'rgb(52,226,226)', 'rgb(238,238,236)']
rewrap-on-resize=true
use-custom-command=false
use-system-font=false
use-theme-colors=false
visible-name='Garuda'
